version: "3.5"

volumes:
  postgres-data: {}

services:
  api:
    build: ./api
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:not-secret@postgres:5432/bestbet
      - ENVIRONMENT=dev
      - CORS_ALLOWED_ORIGINS=["http://localhost:3000"]
      - JWT_BASE=notsecret
    volumes:
      - ./api:/server
    ports:
      - "8000:8000"
    depends_on: 
      postgres:
        condition: "service_healthy"

    command: >
      /bin/sh -c " \
        alembic upgrade head; \
        uvicorn app:app --host=0.0.0.0 --reload
      "

  postgres:
    image: postgres:10-bullseye
    volumes:
      - postgres-data:/var/lib/postgresql
    environment:
      POSTGRES_DB: "bestbet"
      POSTGRES_PASSWORD: "not-secret"
      POSTGRES_USER: "postgres"
    restart: always
    ports:
      - "5440:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 10s
      retries: 120
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"